// READING A WHOLE THREAD BACK.
//
// Sending a message and reading its answer is one turn. This is the other
// half of "operate a thread": recovering everything that is already in one -
// every message, in order, with the files attached to and generated by it.
//
// WHY THIS IS NOT `document.querySelectorAll(...)`:
//
// These UIs VIRTUALIZE. A long thread keeps only the messages near the
// viewport mounted and recycles the rest, so one snapshot of the DOM is a
// window onto the thread, never the thread. Worse, the history is not
// fetched as a document we could read instead: on the ChatGPT build measured
// on 2026-09-06, loading a thread's native URL sends
// `POST /backend-api/f/conversation/prepare`, whose response is only
// `{status, conduit_token}` - the messages then arrive over the app's own
// runtime and materialize as DOM. There is no history JSON to prefer.
//
// So the thread is recovered by SCROLLING it: walk to the top until nothing
// more loads, then walk down collecting at every viewport, keyed on whatever
// stable identity the provider gives its messages. Two properties matter:
//
//   ORDER      established by a single continuous top->bottom walk. First
//              sight is chronological. Collecting during the upward pass and
//              trusting insertion order is not: it starts wherever the
//              viewport happened to be.
//   COMPLETENESS  claimed only when both ends were physically reached and a
//              further pass added nothing. Anything less is reported as
//              incomplete rather than passed off as the whole thread - a
//              half-exported history that claims to be complete is the kind
//              of silent wrongness this project exists to avoid.
//
// Nothing here knows a provider. The message node, and which attributes
// carry identity/role/model, come from `thread.export` in a selectors file.

import { sleep } from '../core/async.mjs'

/**
 * One page-side step: optionally scroll, then report what is mounted.
 *
 * Deliberately ONE round trip that both moves and reads, and deliberately
 * `page.evaluate` rather than a locator: a locator resolves an element
 * first, and in a virtualized list the element it resolved can be recycled
 * out of the document before the call runs.
 */
const STEP = (arg) => {
  const { contract, action, value } = arg
  const nodes = [...document.querySelectorAll(contract.messageNode)]

  // The scrolling ancestor, found from a mounted message and cached. The
  // page's own scrollingElement is usually NOT it: these apps scroll an
  // inner pane.
  const findScroller = () => {
    const cached = window.__ubScroller
    if (cached && document.contains(cached) && cached.scrollHeight > cached.clientHeight + 8) return cached
    let node = nodes[0]?.parentElement ?? null
    while (node) {
      const style = getComputedStyle(node)
      if (node.scrollHeight > node.clientHeight + 8 && /(auto|scroll)/.test(style.overflowY)) {
        window.__ubScroller = node
        return node
      }
      node = node.parentElement
    }
    return document.scrollingElement
  }

  const scroller = findScroller()
  const max = Math.max(0, scroller.scrollHeight - scroller.clientHeight)
  if (action === 'top') scroller.scrollTop = 0
  else if (action === 'bottom') scroller.scrollTop = scroller.scrollHeight
  else if (action === 'to') scroller.scrollTop = Math.max(0, Math.min(max, value))

  const attr = (el, name) => (name ? el.getAttribute(name) : null)

  // IDENTITY, in the order of preference the contract declares.
  //
  // Not every provider marks every message. On the Gemini build measured on
  // 2026-09-06 the model's reply carries
  // `message-content id="message-content-id-r_819b..."` while the user's
  // question carries no id at all - so a user message borrows the id of the
  // reply it is paired with (`pairId`), which is stable, rather than falling
  // back to hashing its text (which would merge two identical questions).
  const ownId = (el) => {
    if (!contract.idAttr) return null
    const direct = attr(el, contract.idAttr)
    if (direct) return direct
    const inner = contract.idNode ? el.querySelector(contract.idNode) : null
    return inner ? attr(inner, contract.idAttr) : null
  }
  const ids = nodes.map(ownId)
  if (contract.pairId === 'next') {
    for (let i = 0; i < ids.length; i++) {
      if (!ids[i] && ids[i + 1]) ids[i] = `pair:${ids[i + 1]}`
    }
  }

  const roleOf = (el) => {
    if (contract.roleAttr) {
      const direct = attr(el, contract.roleAttr)
      if (direct) return direct
    }
    for (const [selector, role] of Object.entries(contract.roleMap ?? {})) {
      if (el.matches(selector)) return role
    }
    return null
  }

  const rows = nodes.map((el, index) => {
    const links = [...el.querySelectorAll('a[href]')].map((a) => ({
      href: a.getAttribute('href'),
      label: (a.getAttribute('aria-label') || a.textContent || '').trim().slice(0, 200),
    }))
    const media = [...el.querySelectorAll('img[src], video[src], audio[src], source[src]')].map((e) => ({
      kind: e.tagName.toLowerCase(),
      src: (e.getAttribute('src') || '').slice(0, 300),
      alt: e.getAttribute('alt') || null,
    }))
    // File affordances are whatever the PROVIDER says they are - the same
    // control the single-turn download path uses. No extension allowlist:
    // any file a thread carries must come back, whatever it is.
    const fileControls = contract.fileControl
      ? [...el.querySelectorAll(contract.fileControl)].map((e) =>
          (e.getAttribute('aria-label') || e.textContent || '').trim().slice(0, 200)
        )
      : []
    // THE TEXT, WITHOUT THE SCREEN-READER FURNITURE. Gemini puts an
    // `h5.cdk-visually-hidden` reading "You said" inside the user's own
    // message, so innerText on the container returned every question as
    // "You said X\n\nX". The container is cloned before pruning: the live
    // page is the user's, and an exporter must not edit it.
    const container = (contract.textNode ? el.querySelector(contract.textNode) : null) ?? el
    let text = ''
    if (contract.textExclude) {
      const copy = container.cloneNode(true)
      for (const junk of copy.querySelectorAll(contract.textExclude)) junk.remove()
      // innerText needs layout, which a detached clone has none of, so it is
      // attached out of view, read, and removed.
      copy.style.position = 'fixed'
      copy.style.left = '-99999px'
      copy.setAttribute('aria-hidden', 'true')
      document.body.appendChild(copy)
      text = (copy.innerText || copy.textContent || '').trim()
      copy.remove()
    } else {
      text = (container.innerText || '').trim()
    }

    const attachments = contract.attachmentNode
      ? [...el.querySelectorAll(contract.attachmentNode)].map((a) => ({
          label: (a.getAttribute('aria-label') || a.getAttribute('title') || a.innerText || '').trim().slice(0, 200),
        })).filter((a) => a.label)
      : []

    // BRANCHES. A regenerated answer (or an edited question) leaves the
    // thread with siblings, and the walk only ever sees the ACTIVE one. The
    // pager the UI draws for them ("2/3") is the only honest evidence that
    // other versions exist, so it is read and reported even when they are
    // not visited - an export that silently drops two thirds of a message's
    // versions, without saying so, is a trap for whoever reads it later.
    let branch = null
    if (contract.branchPager) {
      const scope = contract.branchScope ? el.closest(contract.branchScope) ?? el : el
      for (const p of scope.querySelectorAll(contract.branchPager)) {
        const m = (p.innerText || p.textContent || '').match(/(\d+)\s*\/\s*(\d+)/)
        if (m && +m[2] > 0) { branch = { index: +m[1], total: +m[2] } ; break }
      }
    }

    // THE PROVIDER'S OWN TURN NUMBER, when it publishes one.
    //
    // MEASURED 2026-09-09 on a live ChatGPT thread of six messages: a
    // reload mounted `conversation-turn-2` .. `-6` and NEVER mounted turn 1,
    // through 20s of continuous sampling and an explicit scroll to the top
    // of every scrollable ancestor. The thread had 123px of scroll overflow,
    // so the scroll-based evidence was perfectly true - reached_top and
    // reached_bottom both hold - and the export would have been reported
    // COMPLETE while missing the user's first message.
    //
    // Scroll evidence answers "did the walk reach both ends of what the DOM
    // was showing". It cannot answer "was the DOM showing everything". Only
    // the provider's own numbering can, which is why it is read here.
    let ordinal = null
    if (contract.ordinalNode) {
      const host = el.closest(contract.ordinalNode)
      const raw = host ? (contract.ordinalAttr ? host.getAttribute(contract.ordinalAttr) : host.textContent) : null
      const hit = raw == null ? null : String(raw).match(new RegExp(contract.ordinalPattern || '(\\d+)'))
      if (hit) ordinal = Number(hit[1])
    }

    return {
      id: ids[index],
      ordinal,
      role: roleOf(el),
      branch,
      model_slug: attr(el, contract.modelAttr),
      text,
      // WHERE THIS TEXT CAME FROM. A live ChatGPT answer is read off the
      // wire and is the model's own markdown; an exported one is read back
      // out of the rendered page, so fences and tables are reconstructed and
      // maths may be glyphs. Same field name, different provenance - saying
      // so is cheaper than a reader discovering it in a meta-analysis.
      text_source: 'rendered',
      links,
      media,
      attachments,
      file_controls: [...new Set(fileControls.filter(Boolean))],
    }
  })

  return {
    rows,
    scroll: { top: scroller.scrollTop, max, height: scroller.scrollHeight, viewport: scroller.clientHeight },
    mounted: nodes.length,
  }
}

/** Stable-ish identity when the provider exposes none: role + its text. */
export function contentKey(row) {
  const basis = `${row.role ?? '?'}:${(row.text ?? '').replace(/\s+/g, ' ').trim()}`
  let h = 5381
  for (let i = 0; i < basis.length; i++) h = ((h << 5) + h + basis.charCodeAt(i)) | 0
  return `c${(h >>> 0).toString(36)}:${basis.length}`
}

/** The key a row is remembered by. `stable` says whether the provider gave it. */
export function rowKey(row, contract) {
  if (contract.idAttr && row.id) return { key: row.id, stable: true }
  return { key: contentKey(row), stable: false }
}

/**
 * Fold a page reading into the store, and extend the running order.
 *
 * Pure, so ordering and de-duplication can be tested without a browser -
 * they are the parts that decide whether an export is trustworthy.
 *
 * A row seen again REPLACES the stored copy only when it carries more text:
 * a message can be mounted while still rendering, and the fuller reading is
 * the true one. Its position never moves.
 */
/**
 * Splice one reading's DOM order into the running order.
 *
 * WHY STITCHING RATHER THAN "FIRST SIGHT WINS": what a reading gives is a
 * contiguous run of the thread in document order, and document order is
 * authoritative. Appending keys in the order they were first noticed is not:
 * measured on a 32-message ChatGPT thread, a jump to the top returned a
 * reading in which the LAST three messages were still mounted, so the export
 * came back with the final turns sitting in front of the first ones.
 *
 * Each unplaced key is inserted directly after the last key of this run that
 * is already placed, which keeps a run's internal order intact and anchors
 * it to the part of the thread already known. A run sharing nothing with
 * what is known is appended - and the verification pass below is what
 * notices if that guess was wrong.
 */
export function stitchRun(order, run) {
  const index = new Map(order.map((k, i) => [k, i]))
  let cursor = -1
  for (const key of run) {
    const at = index.get(key)
    if (at !== undefined) {
      cursor = at
      continue
    }
    const insertAt = cursor < 0 ? order.length : cursor + 1
    order.splice(insertAt, 0, key)
    index.clear()
    for (let i = 0; i < order.length; i++) index.set(order[i], i)
    cursor = insertAt
  }
  return order
}

/** Rows of one reading, in document order, as store keys. */
export function readingKeys(rows, contract) {
  return rows.filter((r) => r.role || r.text).map((r) => rowKey(r, contract).key)
}

export function mergeReading(store, order, rows, contract) {
  let added = 0
  for (const row of rows) {
    if (!row.role && !row.text) continue
    const { key, stable } = rowKey(row, contract)
    const prior = store.get(key)
    if (!prior) {
      store.set(key, { ...row, key, stable_id: stable })
      added++
    } else if ((row.text ?? '').length > (prior.text ?? '').length) {
      store.set(key, { ...prior, ...row, key, stable_id: stable })
    }
  }
  if (order) stitchRun(order, readingKeys(rows, contract))
  return added
}

/**
 * Does the global order agree with what this reading shows?
 *
 * The only cheap, honest check available: restrict the known order to the
 * keys in this reading and compare with the reading's own document order.
 * A disagreement means the export is not a faithful transcript, and saying
 * so is the whole point - a thread export that quietly reorders a
 * conversation is worse than one that admits it failed.
 */
export function readingAgrees(order, run) {
  const inRun = new Set(run)
  const projected = order.filter((k) => inRun.has(k))
  const seen = run.filter((k) => order.includes(k))
  return projected.length === seen.length && projected.every((k, i) => k === seen[i])
}

/** The messages in thread order, as plain data. */
export function orderedMessages(store, order) {
  const seen = new Set()
  const out = []
  for (const key of order) {
    if (seen.has(key)) continue
    seen.add(key)
    const row = store.get(key)
    if (row) out.push(row)
  }
  // Anything discovered but never placed by the ordering walk still belongs
  // in the export; it is appended rather than dropped, and the export is not
  // called complete when that happens.
  for (const [key, row] of store) if (!seen.has(key)) out.push({ ...row, order_unknown: true })
  return out
}

/**
 * Walk a thread and return every message in it.
 *
 * `contract` is `thread.export` from a selectors file:
 *   messageNode  selector matching one message
 *   idAttr       attribute carrying a stable provider id (optional)
 *   idNode       descendant carrying that attribute, when the message does
 *                not carry it itself (optional)
 *   pairId       'next' to let an id-less message borrow the id of the
 *                message after it (optional)
 *   roleAttr     attribute carrying the author role (optional)
 *   roleMap      { selector: role } when the role is the element itself
 *   modelAttr    attribute carrying the model that wrote it (optional)
 *   textNode     inner node holding the text (optional; else the message)
 *   fileControl  selector for a file/download control inside a message
 */
export async function sweepThread(page, contract, { settleMs = 400, maxTopPasses = 40, maxSteps = 400, log } = {}) {
  const step = (action, value) => page.evaluate(STEP, { contract, action, value })
  const quietMs = Math.min(settleMs, 200)

  /**
   * Read only once the mounted set has stopped changing.
   *
   * A virtualized list recycles nodes asynchronously, so the reading taken
   * immediately after a jump can still be showing the messages from where
   * the scroller came FROM. Measured: a jump to the top of a 32-message
   * ChatGPT thread returned the last three messages, which then anchored the
   * whole export in the wrong place. Waiting for two identical readings at
   * the same offset is what makes a reading mean what it says.
   */
  // MOUNTED IS NOT THE SAME AS RENDERED. Keyed on identity alone, a message
  // that has arrived but has not yet drawn its attachment chip or its
  // download button looks identical in two consecutive readings, so the walk
  // calls it settled and moves on - and whatever had not rendered yet is
  // simply absent from the export. Measured twice on 2026-09-09: a Gemini
  // turn exported with no attachment on a request that demonstrably sent one
  // as a file, and a ChatGPT thread whose generated file had no download
  // control by the time its message was revisited. Folding the shape of each
  // row into the fingerprint makes "settled" mean the content stopped
  // changing, not merely that the same messages are present.
  const shape = (row) =>
    `${row.attachments?.length ?? 0}a${row.fileControls?.length ?? 0}f${row.media?.length ?? 0}m${(row.text ?? '').length}`
  const fingerprint = (r) =>
    `${r.scroll.top}:${readingKeys(r.rows, contract).join('|')}:${r.rows.map(shape).join('|')}`
  async function settledReading(tries = 5) {
    let prev = await step()
    for (let i = 1; i < tries; i++) {
      await sleep(quietMs)
      const next = await step()
      if (fingerprint(next) === fingerprint(prev)) return next
      prev = next
    }
    return prev
  }

  const store = new Map()
  const order = []
  // Every turn number this walk ever saw, across every reading. Accumulated
  // rather than sampled once: on a virtualized thread the mounted slice
  // legitimately starts above 1, and it is the union over the whole sweep
  // that says whether the beginning of the thread was ever shown.
  const ordinals = new Set()
  const merge = (into, rows) => {
    for (const r of rows ?? []) if (Number.isFinite(r.ordinal)) ordinals.add(r.ordinal)
    mergeReading(store, into, rows, contract)
  }
  let reachedTop = false
  let reachedBottom = false

  // UP FIRST, in repeated jumps. A virtualized list loads more history as
  // the top comes into view, so one jump to zero proves nothing: keep going
  // until neither the scroll height nor the message set changes.
  let last = await step('bottom')
  merge([], last.rows)
  let stable = 0
  for (let pass = 0; pass < maxTopPasses; pass++) {
    const before = { height: last.scroll.height, size: store.size }
    last = await step('top')
    await sleep(settleMs)
    last = await step()
    merge([], last.rows)
    const grew = last.scroll.height !== before.height || store.size !== before.size
    if (last.scroll.top <= 2 && !grew) {
      stable++
      // Two consecutive quiet passes at the top: history has stopped
      // arriving. One is not enough - the first can land in a gap between
      // fetches.
      if (stable >= 2) {
        reachedTop = true
        break
      }
    } else {
      stable = 0
    }
  }
  log?.debug(`thread sweep: top ${reachedTop ? 'reached' : 'NOT reached'}, ${store.size} message(s) after hydrating upward`)

  // DOWN ONCE, continuously. Every reading is STITCHED, not appended: see
  // stitchRun above for why first-sight order is not thread order.
  order.length = 0
  const runs = []
  await step('top')
  for (let i = 0; i < maxSteps; i++) {
    last = await settledReading()
    const run = readingKeys(last.rows, contract)
    runs.push(run)
    merge(order, last.rows)
    if (last.scroll.top >= last.scroll.max - 2) {
      // Confirm the bottom is really the bottom: content can still be
      // arriving below.
      await sleep(settleMs)
      const confirm = await settledReading()
      runs.push(readingKeys(confirm.rows, contract))
      merge(order, confirm.rows)
      if (confirm.scroll.top >= confirm.scroll.max - 2) {
        reachedBottom = true
        last = confirm
        break
      }
      last = confirm
    }
    // Overlap the steps by a third of a viewport: a message taller than the
    // step would otherwise be skipped between two readings. The overlap is
    // also what anchors the next run to the order already built.
    const stride = Math.max(200, Math.floor(last.scroll.viewport * 0.66))
    await step('to', last.scroll.top + stride)
    await sleep(settleMs)
  }

  // VERIFY the order against every reading taken. Each reading saw a
  // contiguous slice of the thread in the DOM's own order; if the assembled
  // order contradicts any of them, the transcript is not faithful and must
  // not be presented as one.
  const disagreements = runs.filter((run) => !readingAgrees(order, run)).length
  if (disagreements) {
    log?.warn(
      `thread sweep: ${disagreements} of ${runs.length} readings disagree with the assembled order - ` +
        'the export is reported as unverified rather than as a faithful transcript'
    )
  }

  const messages = orderedMessages(store, order)
  const placed = messages.filter((m) => !m.order_unknown).length

  // THE PROVIDER'S OWN NUMBERING, if it publishes one, has the final say on
  // completeness. Turn numbers that start at 1 and run without a hole are
  // the only positive evidence that the beginning of the thread was shown at
  // all; scrolling to the top of a pane that never held the first message
  // proves nothing. A provider with no numbering contributes nothing here
  // (empty set), and completeness falls back to the scroll evidence alone.
  const seenOrdinals = [...ordinals].sort((a, b) => a - b)
  const ordinalGaps = seenOrdinals.length
    ? seenOrdinals[seenOrdinals.length - 1] - seenOrdinals[0] + 1 - seenOrdinals.length
    : 0
  const ordinalsWhole = seenOrdinals.length === 0 || (seenOrdinals[0] === 1 && ordinalGaps === 0)
  if (!ordinalsWhole) {
    log?.warn(
      `thread sweep: the provider numbers its turns from ${seenOrdinals[0]}` +
        `${ordinalGaps ? ` with ${ordinalGaps} missing in between` : ''} - ` +
        `${messages.length} message(s) were walked, but the thread does not start at turn 1, ` +
        'so this export is reported as incomplete'
    )
  }

  return {
    messages,
    evidence: {
      reached_top: reachedTop,
      reached_bottom: reachedBottom,
      message_count: messages.length,
      ordered_count: placed,
      // Whether identity came from the provider or was inferred from content.
      // With inferred keys, two identical messages collapse into one, and a
      // caller deserves to know that before trusting a count.
      stable_ids: messages.length > 0 && messages.every((m) => m.stable_id),
      // How many messages have versions this walk did NOT visit, and
      // whether anything was done about it. `branch_pager: false` means the
      // provider has no measured pager, so the question was never asked -
      // which is not the same as "there are none".
      branch_pager: !!contract.branchPager,
      branched_messages: messages.filter((m) => (m.branch?.total ?? 1) > 1).length,
      branches_walked: false,
      mounted_at_end: last?.mounted ?? 0,
      readings: runs.length,
      order_verified: disagreements === 0,
      // The provider's own turn numbers. `first_turn: null` means this
      // provider publishes none, so the question could not be asked -
      // which is not the same as "the thread starts where we think".
      first_turn: seenOrdinals.length ? seenOrdinals[0] : null,
      last_turn: seenOrdinals.length ? seenOrdinals[seenOrdinals.length - 1] : null,
      turn_gaps: seenOrdinals.length ? ordinalGaps : null,
    },
    complete:
      reachedTop && reachedBottom && placed === messages.length && disagreements === 0 && ordinalsWhole,
  }
}

/**
 * Bring one message back into the DOM and return true when it is mounted.
 *
 * Virtualization is not only an export problem: a file generated forty
 * messages ago has no download control in the document at all until its
 * message is scrolled back into view. Walking down from the top in strides
 * is the same motion the sweep uses, so it costs nothing new to reuse it.
 */
export async function mountMessage(page, contract, selector, { settleMs = 300, maxSteps = 400 } = {}) {
  const step = (action, value) => page.evaluate(STEP, { contract, action, value })
  const present = () => page.locator(selector).count().then((n) => n > 0).catch(() => false)

  if (await present()) return true
  let last = await step('top')
  await sleep(settleMs)
  for (let i = 0; i < maxSteps; i++) {
    if (await present()) return true
    if (last.scroll.top >= last.scroll.max - 2) return present()
    const stride = Math.max(200, Math.floor(last.scroll.viewport * 0.66))
    last = await step('to', last.scroll.top + stride)
    await sleep(settleMs)
  }
  return present()
}
